{"asctime": "2025-04-25 15:31:08,858", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 15:47:39,137", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:09:04,076", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:15:01,840", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:23:51,939", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:29:32,783", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:30:10,694", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:30:18,878", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:44:40,862", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:49:44,672", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 16:52:02,871", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 20:36:13,234", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 20:38:21,216", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 20:40:13,945", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 20:41:50,314", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-25 21:11:22,307", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-26 11:46:34,622", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-26 12:04:07,884", "levelname": "DEBUG", "name": "asyncio", "message": "Using selector: SelectSelector", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\selector_events.py", "lineno": 54}
{"asctime": "2025-04-26 12:33:55,780", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 12:36:02,755", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 12:36:15,726", "levelname": "ERROR", "name": "asyncio", "message": "Task exception was never retrieved\nfuture: <Task finished name='Task-3' coro=<monitor_shutdown() done, defined at C:\\Users\\caleb\\Projects\\refacto-ai\\src\\app\\main.py:17> exception=KeyboardInterrupt()>", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py", "lineno": 1758, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\caleb\\Projects\\refacto-ai\\run.py\", line 24, in <module>\n    asyncio.run(main())\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"C:\\Users\\caleb\\Projects\\refacto-ai\\src\\app\\main.py\", line 22, in monitor_shutdown\n    raise KeyboardInterrupt\nKeyboardInterrupt"}
{"asctime": "2025-04-26 12:40:34,873", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 12:41:21,697", "levelname": "ERROR", "name": "asyncio", "message": "Task exception was never retrieved\nfuture: <Task finished name='Task-3' coro=<monitor_shutdown() done, defined at C:\\Users\\caleb\\Projects\\refacto-ai\\src\\app\\main.py:17> exception=KeyboardInterrupt()>", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py", "lineno": 1758, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\caleb\\Projects\\refacto-ai\\run.py\", line 24, in <module>\n    asyncio.run(main())\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File \"C:\\Users\\caleb\\Projects\\refacto-ai\\src\\app\\main.py\", line 22, in monitor_shutdown\n    raise KeyboardInterrupt\nKeyboardInterrupt"}
{"asctime": "2025-04-26 12:54:11,710", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 13:03:13,363", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 13:03:27,001", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 13:04:30,837", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 13:05:11,424", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
{"asctime": "2025-04-26 13:06:22,015", "levelname": "DEBUG", "name": "asyncio", "message": "Using proactor: IocpProactor", "pathname": "C:\\Users\\caleb\\.conda\\envs\\refacto-ai\\lib\\asyncio\\proactor_events.py", "lineno": 630}
